name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-14
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: SwiftPM Cache
        uses: actions/cache@v4
        with:
          path: ./PluginTests/ExamplePackage/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('./PluginTests/ExamplePackage/Package.resolved') }}
      - name: xcodebuild test
        run: |
          (
            cd PluginTests/ExamplePackage
            xcodebuild -scheme ExamplePackage -sdk macosx -destination "platform=macOS,arch=$(uname -m)" -clonedSourcePackagesDirPath SourcePackages -skipPackagePluginValidation test
          )
      - name: swift test
        run: |
          (
            cd PluginTests/ExamplePackage
            swift test
          )
